---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: pelorus-ui
    app.kubernetes.io/component: pelorus-ui
    app.kubernetes.io/instance: pelorus-ui
    app.kubernetes.io/name: pelorus-ui
    app.kubernetes.io/part-of: pelorus
  name: pelorus-ui
  namespace: pelorus-api
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/etsauer/pelorus-ui:dev
    from:
      kind: DockerImage
      name: quay.io/etsauer/pelorus-ui:dev
    importPolicy:
      importMode: Legacy
    name: dev
    referencePolicy:
      type: Local
