apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
   serviceaccounts.openshift.io/oauth-redirecturi.first:  "api/auth/callback/openshift"
   serviceaccounts.openshift.io/oauth-redirectreference.first: "{\"kind\":\"OAuthRedirectReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"Route\",\"name\":\"pelorus-ui\"}}"
  name: pelorus
  namespace: pelorus-api